language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

script: phpunit tests/test.php

install:
    - composer update -o
    - npm install -g bower
    - bower install
    - phpunit --version

matrix:
    allow_failures:
        - php: 5.6