language: php

php:
    - 5.5
    - 5.6
    - 7.0

script: phpunit tests/test.php

install:
    - composer update -o
    - npm install -g bower
    - bower install
    - phpunit --version

matrix:
    allow_failures:
        - php: 7.0